#!/bin/sh

# default programs
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"

# xdg folders
# https://wiki.archlinux.org/title/XDG_Base_Directory
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

# add programming tools to path
export DENO_INSTALL="$XDG_DATA_HOME/deno"
export CARGO_HOME="$XDG_CACHE_HOME/cargo"
export GOPATH="$HOME/code/go"
export GOROOT="/usr/local/go"
export PATH="$PATH:$GOROOT/bin:$GOPATH/bin:$CARGO_HOME/bin:$DENO_INSTALL/bin"
source "$CARGO_HOME/env"

# more path
export PATH="$PATH:$HOME/.local/bin"
